### ISSUE TITLE
Line doesn't move on window resize

### ISSUE THREAD

**Issue by neilgarb** [SwiftySpartan/ng-smart-tabs#1]
Example: 

![image](https://user-images.githubusercontent.com/598376/58808655-57146b00-8612-11e9-9810-8fb967dd7b34.png)

If I click on one of the items, it lines up correctly. If I resize the window, the line stays but the links move.

**Comment by andrewwormald** [comment]
Thank you for logging this issue. It has been resolved from v1.1.5.

https://www.npmjs.com/package/ng-smart-tabs/v/1.1.5

**Comment by neilgarb** [comment]
Thanks for the speedy rectification.

**Comment by dunxen** [comment]
Indeed. Many thanks kind sir.
